- name: Initialize cluster
  hosts: controlplane
  remote_user: root

  tasks:
    - name: Initialize a new cluster
      changed_when: true
      ansible.builtin.command:
        cmd: kubeadm init
      register: kubeadmout
    - name: Create .kube in root
      ansible.builtin.file:
        path: /root/.kube
        mode: '0600'
        state: directory
    - name: Copy admin.conf to config
      ansible.builtin.file:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        owner: root
        group: root
    - name: Display kubeadm
      ansible.builtin.debug:
        msg: "{{ kubeadmout }}"
